baseurl = "https://daxdax89.com"
title = "DaX"

theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "DaX"

[params]
    author = "DaX"
    description = "My personal website"
    keywords = "blog,developer,personal, coder, programmer, web developer"
    info = "Full Stack Developer"
    avatarurl = "images/avatar.png"
    footercontent = "Coded and simplified by DaX"

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Custom CSS
    custom_css = ["/css/main.css"]

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/daxdax89/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 2
    url = "https://instagram.com/daxdax89/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/daxdax89/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/daxdax89/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Contact me"
    weight = 5
    url = "/contact/"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "<DaX/>"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "DaX"
        info = "Full Stack Developer"
        description = "My personal website"
        keywords = "blog,developer,personal, coder, web dev, programmer, full stack"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2.0
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"
        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "/contact/"


    [languages.rs]
        languagename = "Srpski"
        title = "<DaX/>"

        [languages.rs.params]
            author = "DaX"
            description = "Moj licni website"
            keywords = "blog,developer,koder, programer, web developer"
            info = "Full Stack Programer"

        [languages.rs.menu]

            [[languages.rs.menu.main]]
            name = "O meni"
            weight = 1.0
            url = "/rs/o-meni/"

            [[languages.rs.menu.main]]
            name = "Blog"
            weight = 2.0
            url = "/rs/posts/"

            [[languages.rs.menu.main]]
            name = "Projekti"
            weight = 3
            url = "/projekti/"
            [[languages.rs.menu.main]]
            name = "Kontakt"
            weight = 5
            url = "/kontakt/"